name: CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - run: git config --global core.autocrlf input
      - uses: cygwin/cygwin-install-action@master
        with:
          packages: |
            cygutils-extra
            cmake
            cygport
            flexdll
            gdb
            git
            make
            ninja
            ocaml
            python3
            libxml2-devel
            zlib-devel
            libzstd-devel
            vim
            python39-sphinx
            python39-pytz
            libcurl-devel
            libpcre2-devel
            libssh2-devel
            libssl-devel=3.0.16-2
            libssl3=3.0.16-2
            openssl=3.0.16-2

      - name: asdf
        run: |
          git clone -b playground https://cygwin.com/git/cygwin-packages/libgit2
          git clone -b playground https://cygwin.com/git/cygwin-packages/llvm
          cd libgit2
          cygport libgit2.cygport all-test
          cd ../llvm
          BOOTSTRAP=ON cygport llvm.cygport all-test
        shell: d:\cygwin\bin\bash.exe -eo pipefail -o igncr '{0}'

      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            llvm/llvm-*.x86_64/dist
            libgit2/libgit2-*.x86_64/
