name: Build LLD
on:
  workflow_dispatch:

jobs:
  artifacts:
    runs-on: ubuntu-latest
    outputs:
      llvm_version: ${{ steps.versions.outputs.llvm_version }}
      clang_version: ${{ steps.versions.outputs.clang_version }}

    steps:
      - uses: dawidd6/action-download-artifact@v11
        with:
          workflow: bootstrap_llvm.yml
          workflow_conclusion: success
          branch: ${{ github.ref_name }}
          name: packages
          path: pkgs
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - id: versions
        name: versions
        run: cat pkgs/llvm_version.txt >> "$GITHUB_OUTPUT"

      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            pkgs/


  lld:
    runs-on: windows-latest
    needs: artifacts
    steps:
      - run: git config --global core.autocrlf input
      - uses: actions/download-artifact@v5
        with:
          name: packages
          path: pkgs
      - id: cache-restore
        uses: actions/cache/restore@v4
        with:
          key: cygwin-packages-
          restore-keys: |
            cygwin-packages-
          path: cygwin-packages
      - run: IF EXIST cygwin-packages move /y cygwin-packages D:\
        shell: cmd
      - id: cygwin
        uses: cygwin/cygwin-install-action@master
        with:
          site: >-
            http://mirrors.kernel.org/sourceware/cygwin/
            file://${{ github.workspace }}/pkgs
          check-sig: false
          packages: |
            cygutils-extra
            cmake
            calm
            cygport
            flexdll
            gdb
            git
            make
            ninja
            ocaml
            python3
            libxml2-devel
            zlib-devel
            libzstd-devel
            vim
            python39-sphinx
            python39-pytz
            libpcre2-devel
            libssh2-devel
            libssl-devel
            libpolly-devel=${{ needs.artifacts.outputs.llvm_version }}
            clang=${{ needs.artifacts.outputs.clang_version }}

      - name: prepare cache
        run: |
          if (Test-Path `${{ steps.cygwin.outputs.package-cache }}\file`* ) {
            rm -r -fo `${{ steps.cygwin.outputs.package-cache }}\file`*
          }
          move "${{ steps.cygwin.outputs.package-cache }}" .
      - uses: actions/cache/save@v4
        if: ${{ steps.cache-restore.outputs.cache-matched-key != format('cygwin-packages-{0}', hashFiles('cygwin-packages/**', '!cygwin-packages/**/setup.ini')) }}
        with:
          key: cygwin-packages-${{ hashFiles('cygwin-packages/**', '!cygwin-packages/**/setup.ini') }}
          path: cygwin-packages
      - name: post cache
        run: move /Y cygwin-packages "${{ steps.cygwin.outputs.package-cache }}"
        shell: cmd

      - name: build
        run: |
          export PATH=/usr/local/bin:/usr/bin:/bin:$PATH
          mv "$(cygpath -u '${{github.workspace}}')/pkgs" .
          mkdir -p pkgs/x86_64/release
          git clone -b 21.1 https://cygwin.com/git/cygwin-packages/lld
          cd lld
          pip3 install --user myst_parser
          cygport lld.cygport download all-test
          cp -Rf lld-*.x86_64/dist/* ../pkgs/x86_64/release
          cd ../pkgs
          mksetupini --arch x86_64 --inifile=x86_64/setup.ini --releasearea=. --disable-check=missing-required-package,missing-depended-package,missing-build-depended-package,missing-curr
          bzip2 <x86_64/setup.ini >x86_64/setup.bz2
          xz -6e <x86_64/setup.ini >x86_64/setup.xz
        shell: d:\cygwin\bin\bash.exe -leo pipefail -o igncr '{0}'

      - uses: actions/upload-artifact@v4
        with:
          name: packages
          overwrite: true
          path: |
            ${{steps.cygwin.outputs.root}}/home/runneradmin/pkgs/

      - run: DEL /F ${{ steps.cygwin.outputs.root }}\bin\git.exe
        if: always()
        shell: cmd
