name: Build LLD
on:
  workflow_dispatch:

env:
  LLVM_VERSION: 20.1.8-2

jobs:
  lld:
    runs-on: windows-latest
    steps:
      - run: git config --global core.autocrlf input
      - uses: dawidd6/action-download-artifact@v11
        with:
          repo: jeremyd2019/cygwin
          workflow: cygwin.yml
          workflow_conclusion: success
          branch: cygwin-3.6.4-posix-spawn
          event: push
          name: cygwin-install-x86_64
          path: test-cygwin
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - id: cache-restore
        uses: actions/cache/restore@v4
        with:
          key: cygwin-packages-
          restore-keys: |
            cygwin-packages-
          path: cygwin-packages
      - run: IF EXIST cygwin-packages move /y cygwin-packages D:\
        shell: cmd
      - id: cygwin
        uses: cygwin/cygwin-install-action@master
        with:
          packages: |
            cygutils-extra
            cmake
            calm
            cygport
            flexdll
            gdb
            git
            make
            ninja
            ocaml
            python3
            libxml2-devel
            zlib-devel
            libzstd-devel
            vim
            python39-sphinx
            python39-pytz
            libpcre2-devel
            libssh2-devel
            libssl-devel
            libpolly-devel=${{ env.LLVM_VERSION }}
            clang=${{ env.LLVM_VERSION }}
      - name: update cygwin
        env:
          CHERE_INVOKING: 1
        shell: c:/msys64/usr/bin/bash.exe -leo pipefail '{0}'
        run: |
          cp -f test-cygwin/bin/cygwin1.dll /d/cygwin/bin/cygwin1.dll

      - name: prepare cache
        run: |
          if (Test-Path `${{ steps.cygwin.outputs.package-cache }}\file`* ) {
            rm -r -fo `${{ steps.cygwin.outputs.package-cache }}\file`*
          }
          move "${{ steps.cygwin.outputs.package-cache }}" .
      - uses: actions/cache/save@v4
        if: ${{ steps.cache-restore.outputs.cache-matched-key != format('cygwin-packages-{0}', hashFiles('cygwin-packages/**', '!cygwin-packages/**/setup.ini')) }}
        with:
          key: cygwin-packages-${{ hashFiles('cygwin-packages/**', '!cygwin-packages/**/setup.ini') }}
          path: cygwin-packages
      - name: post cache
        run: move /Y cygwin-packages "${{ steps.cygwin.outputs.package-cache }}"
        shell: cmd

      - name: build
        run: |
          export PATH=/usr/local/bin:/usr/bin:/bin:$PATH
          mkdir -p pkgs/x86_64/release
          git clone -b playground https://cygwin.com/git/cygwin-packages/lld
          cd lld
          pip3 install --user myst_parser
          cygport lld.cygport download all-test
          cp -Rf lld-*.x86_64/dist/* ../pkgs/x86_64/release
          cd ../pkgs
          mksetupini --arch x86_64 --inifile=x86_64/setup.ini --releasearea=. --disable-check=missing-required-package,missing-depended-package,missing-build-depended-package,missing-curr
          bzip2 <x86_64/setup.ini >x86_64/setup.bz2
          xz -6e <x86_64/setup.ini >x86_64/setup.xz
        shell: d:\cygwin\bin\bash.exe -leo pipefail -o igncr '{0}'

      - uses: actions/upload-artifact@v4
        with:
          name: packages
          overwrite: true
          path: |
            ${{steps.cygwin.outputs.root}}/home/runneradmin/pkgs/

      - run: DEL /F ${{ steps.cygwin.outputs.root }}\bin\git.exe
        if: always()
        shell: cmd
